version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/app
    stdin_open: true
    tty: true
   
volumes:
  public:
    driver: local
