version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - ${WEB_PORT:-3000}:3000
    volumes:
      - .:/app
    stdin_open: true
    tty: true
   
volumes:
  public:
    driver: local
